version: '4'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: chatapprt-backend
    container_name: chatapprt-backend
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file: ./backend/.env
    environment:
      - MONGO_DB_URI=mongodb://mongo:27017/chat-app-rt
      - JWT_SECRET=secret
    networks:
      - app-network
  mongo:
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: chatapprt-frontend
    container_name: chatapprt-frontend
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local
